let products=[],siteSettings={},cart=JSON.parse(localStorage.getItem("ms_cart")||"[]"),wish=JSON.parse(localStorage.getItem("ms_wish")||"[]"),coupon=localStorage.getItem("ms_coupon")||"";
const $=s=>document.querySelector(s), money=n=>"₹"+Number(n).toLocaleString("en-IN");
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Something went wrong");return j}
async function getProducts(){try{return await api("/api/products")}catch{return await fetch("data/products.json").then(r=>r.json())}}
async function getSettings(){try{return await api("/api/site-settings")}catch{return await fetch("data/site-settings.json").then(r=>r.json())}}
function resolveAsset(src){if(!src)return "";if(/^data:|^https?:\/\//i.test(src))return src;return src}
function save(){localStorage.setItem("ms_cart",JSON.stringify(cart));localStorage.setItem("ms_wish",JSON.stringify(wish));localStorage.setItem("ms_coupon",coupon);counts()}
function counts(){const c=$("#cartCount"),w=$("#wishCount");if(c)c.textContent=cart.reduce((a,x)=>a+x.qty,0);if(w)w.textContent=wish.length}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function card(p){let w=wish.includes(p.id);return `<article class="card"><div class="pic">${p.image?`<img src="${esc(resolveAsset(p.image))}" alt="${esc(p.name)}">`:`<span class="symbol">✦</span>`}<span class="badge">${esc(p.badge||"NEW")}</span><button class="heart ${w?"active":""}" onclick="toggleWish('${p.id}')">${w?"♥":"♡"}</button></div><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.description||"Premium curated pick.")}</p><b class="price">${money(p.price)}</b> <span class="old">${money(p.compareAt)}</span><div class="actions"><button onclick="quick('${p.id}')">Quick View</button><button class="add" onclick="add('${p.id}')">Add to Bag</button></div></div></article>`}
function render(list,target){const el=$(target);if(el)el.innerHTML=list.length?list.map(card).join(""):`<p style="color:#777">No products found.</p>`}
function current(){let a=[...products],c=$("#catFilter")?.value||"",s=$("#sort")?.value||"";if(c)a=a.filter(p=>p.category===c);if(s==="low")a.sort((x,y)=>x.price-y.price);if(s==="high")a.sort((x,y)=>y.price-x.price);if(s==="featured")a.sort((x,y)=>Number(y.featured)-Number(x.featured));return a}
function shop(){render(current(),"#products")}
function add(id){let p=products.find(x=>x.id===id),i=cart.find(x=>x.id===id);if(!p||p.stock<1)return alert("This product is currently out of stock.");if(i){if(i.qty<p.stock)i.qty++;}else cart.push({id,qty:1});save();renderCart();openCart()}
function qty(id,d){let i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];save();shop();render("#newProducts",products.slice().reverse().slice(0,4));render("#bestProducts",products.filter(p=>p.featured).slice(0,4))}
function renderCart(){let box=$("#cartItems");if(!box)return;if(!cart.length){box.innerHTML='<div style="padding:50px;text-align:center;color:#888">Your bag is empty.</div>'}else{box.innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `<div class="line"><div class="thumb">${p?.image?`<img src="${esc(resolveAsset(p.image))}" style="width:100%;height:100%;object-fit:cover">`:"✦"}</div><div><h4>${esc(p?.name||"Product")}</h4><p>${money(p?.price||0)} × ${i.qty}</p><div class="qty"><button onclick="qty('${i.id}',-1)">−</button><b>${i.qty}</b><button onclick="qty('${i.id}',1)">+</button></div></div><b>${money((p?.price||0)*i.qty)}</b></div>`}).join("")}let sub=cart.reduce((a,i)=>a+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0),disc=coupon==="MUSKAN10"?Math.round(sub*.1):0;$("#subtotal").textContent=money(sub);$("#discount").textContent=money(disc);$("#total").textContent=money(sub-disc)}
function openCart(){$("#cart")?.classList.add("open");$("#shade")?.classList.add("show")}function closeCart(){$("#cart")?.classList.remove("open");$("#shade")?.classList.remove("show")}
function quick(id){let p=products.find(x=>x.id===id);if(!p)return;$("#modalBody").innerHTML=`<div class="quick"><div class="quickImg">${p.image?`<img src="${esc(resolveAsset(p.image))}" style="width:100%;height:100%;object-fit:cover">`:"✦"}</div><div><span class="sectionTitle span">${esc(p.badge||"PREMIUM")}</span><h2 style="font:600 32px 'Playfair Display'">${esc(p.name)}</h2><p>${esc(p.description)}</p><h3>${money(p.price)}</h3><p style="color:#777;font-size:12px">Stock available: ${p.stock}</p><button class="btn gold full" onclick="add('${p.id}');closeModal()">Add to Bag</button></div></div>`;$("#modal")?.classList.add("show")}
function closeModal(){$("#modal")?.classList.remove("show")}
async function search(){let q=$("#search")?.value.trim().toLowerCase();if(!q)return;render(products.filter(p=>(p.name+" "+p.category+" "+p.description).toLowerCase().includes(q)),"#products");$("#shop")?.scrollIntoView({behavior:"smooth"})}
function applySettings(){const logo=resolveAsset(siteSettings.logo||"ms-muskan-select-logo.png"),hero=resolveAsset(siteSettings.hero||"hero-luxury.svg");["brandLogo","everLogo","footerLogo"].forEach(id=>{const el=$("#"+id);if(el)el.src=logo});const heroEl=$(".hero");if(heroEl)heroEl.style.backgroundImage=`linear-gradient(90deg,rgba(8,8,8,.92),rgba(8,8,8,.58),rgba(8,8,8,.15)),url("${hero}")`}
async function init(){[products,siteSettings]=await Promise.all([getProducts(),getSettings()]);applySettings();counts();shop();render(products.slice().reverse().slice(0,4),"#newProducts");render(products.filter(p=>p.featured).slice(0,4),"#bestProducts");renderCart();$("#catFilter")?.addEventListener("change",shop);$("#sort")?.addEventListener("change",shop);$("#searchBtn")?.addEventListener("click",search);$("#search")?.addEventListener("keydown",e=>e.key==="Enter"&&search());$("#cartBtn")?.addEventListener("click",openCart);$("#closeCart")?.addEventListener("click",closeCart);$("#shade")?.addEventListener("click",closeCart);$("#closeModal")?.addEventListener("click",closeModal);$("#modal")?.addEventListener("click",e=>e.target.id==="modal"&&closeModal());$("#hamb")?.addEventListener("click",()=>$("#nav")?.classList.toggle("open"));document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{$("#catFilter").value=b.dataset.cat;shop();$("#shop")?.scrollIntoView({behavior:"smooth"})});document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{$("#search").value=b.dataset.q;search()});document.querySelector("[data-ever]")?.addEventListener("click",()=>{render(products.filter(p=>p.everShine),"#products");$("#shop")?.scrollIntoView({behavior:"smooth"})})}
init().catch(e=>console.error("MS Muskan Select init failed:",e));
